version: "3"

env:
  ZIP_NAME: yarmarok-api.zip

tasks:
  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test -v ./...

  integration-test:
    cmds:
      - RUN_INTEGRATION_TESTS=true go test -v ./...
  
  archive:
    deps: [ clean ]
    cmds:
      - git archive --format=zip -o $ZIP_NAME HEAD

  clean:
    cmds:
      - rm $ZIP_NAME
    status:
      - "[ ! -f $ZIP_NAME ]"

  local-run:
    cmds:
      - go test -tags local -timeout 0 -v ./testinfra/local/run_test.go
