version: '3'

env:
  ZIP_NAME: yarmarok-api.zip

tasks:
  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test -v ./...

  integration-test:
    cmds:
      - RUN_INTEGRATION_TESTS=true go test -v ./...   
  
  archive:
    deps: [clean]
    cmds:
      - zip -r $ZIP_NAME .

  clean:
    cmds:
      - rm $ZIP_NAME
    status:
      - "[ ! -f $ZIP_NAME ]" 