// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaznasho/yarmarok/service (interfaces: UserService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/kaznasho/yarmarok/service"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// InitUserIfNotExists mocks base method.
func (m *MockUserService) InitUserIfNotExists(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitUserIfNotExists", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitUserIfNotExists indicates an expected call of InitUserIfNotExists.
func (mr *MockUserServiceMockRecorder) InitUserIfNotExists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitUserIfNotExists", reflect.TypeOf((*MockUserService)(nil).InitUserIfNotExists), arg0)
}

// YarmarokService mocks base method.
func (m *MockUserService) YarmarokService(arg0 string) service.YarmarokService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "YarmarokService", arg0)
	ret0, _ := ret[0].(service.YarmarokService)
	return ret0
}

// YarmarokService indicates an expected call of YarmarokService.
func (mr *MockUserServiceMockRecorder) YarmarokService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "YarmarokService", reflect.TypeOf((*MockUserService)(nil).YarmarokService), arg0)
}
