name: Deploy UI

on:
  workflow_dispatch: { }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./ui
        run: yarn install

      - name: Build
        working-directory: ./ui
        run: yarn generate

      - name: Setup GCP Service Account
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_FUNCTION_DEPLOYMENT_SA }}"

      - name: Upload folder to GCP bucket
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: "./ui/dist"
          destination: "yarmarok-frontend"
