name: Build and test Go code

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "ui/**" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "ui/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
