name: Build and test JS code

on:
  push:
    branches: [ "main" ]
    paths: [ "ui/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "ui/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn ci

      - name: Build
        run: yarn generate

      - name: Archive build UI
        uses: actions/upload-artifact@v3
        with:
          name: ui-dist
          path: dist
